// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Lovable Cloud Supabase instance
const SUPABASE_URL = "https://qycsyvjnynvkuluiyzyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5Y3N5dmpueW52a3VsdWl5enl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxNDI0ODcsImV4cCI6MjA4MzcxODQ4N30.JfsKjbV9I_35iBXsg1iCBSTVYKtywo7LqXMPgZ14m9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
